rerun autotools

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21089,9 +21089,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/CoinUtils/README; then
+		     coin_has_coinutils=installed
+		     COINUTILSINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21153,18 +21154,35 @@ fi
 if test $coin_has_coinutils = installed; then
   echo "$as_me:$LINENO: result: installed in $COINUTILSINSTDIR" >&5
 echo "${ECHO_T}installed in $COINUTILSINSTDIR" >&6
-  # Check for header
+  if test -r $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&5
+echo "$as_me: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
 echo "${ECHO_T}$coin_has_coinutils" >&6
+  if test $coin_has_coinutils != notGiven &&
+     test $coin_has_coinutils != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of CoinUtils" >&5
+echo $ECHO_N "checking for source code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSSRCDIR" >&5
+echo "${ECHO_T}$COINUTILSSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of CoinUtils" >&5
+echo $ECHO_N "checking for object code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSOBJDIR" >&5
+echo "${ECHO_T}$COINUTILSOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory CoinUtils should be recursed into" >&5
 echo $ECHO_N "checking whether directory CoinUtils should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_coinutils" != skipped &&
+  if test "$coin_has_coinutils" != skipping &&
      test "$coin_has_coinutils" != installed; then
     if test -r $srcdir/CoinUtils/configure; then
       coin_subdirs="$coin_subdirs CoinUtils"
@@ -21422,9 +21440,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Clp/README; then
+		     coin_has_clp=installed
+		     CLPINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21486,18 +21505,35 @@ fi
 if test $coin_has_clp = installed; then
   echo "$as_me:$LINENO: result: installed in $CLPINSTDIR" >&5
 echo "${ECHO_T}installed in $CLPINSTDIR" >&6
-  # Check for header
+  if test -r $CLPINSTDIR/share/doc/coin/Clp/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CLPINSTDIR/share/doc/coin/Clp/README should be available if Clp is installed" >&5
+echo "$as_me: error: $CLPINSTDIR/share/doc/coin/Clp/README should be available if Clp is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_clp" >&5
 echo "${ECHO_T}$coin_has_clp" >&6
+  if test $coin_has_clp != notGiven &&
+     test $coin_has_clp != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Clp" >&5
+echo $ECHO_N "checking for source code location of Clp... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CLPSRCDIR" >&5
+echo "${ECHO_T}$CLPSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Clp" >&5
+echo $ECHO_N "checking for object code location of Clp... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CLPOBJDIR" >&5
+echo "${ECHO_T}$CLPOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory Clp should be recursed into" >&5
 echo $ECHO_N "checking whether directory Clp should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_clp" != skipped &&
+  if test "$coin_has_clp" != skipping &&
      test "$coin_has_clp" != installed; then
     if test -r $srcdir/Clp/configure; then
       coin_subdirs="$coin_subdirs Clp"
@@ -21626,9 +21662,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of DyLP with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of DyLP with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/DyLP/README; then
+		     coin_has_dylp=installed
+		     DYLPINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21690,18 +21727,35 @@ fi
 if test $coin_has_dylp = installed; then
   echo "$as_me:$LINENO: result: installed in $DYLPINSTDIR" >&5
 echo "${ECHO_T}installed in $DYLPINSTDIR" >&6
-  # Check for header
+  if test -r $DYLPINSTDIR/share/doc/coin/DyLP/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $DYLPINSTDIR/share/doc/coin/DyLP/README should be available if DyLP is installed" >&5
+echo "$as_me: error: $DYLPINSTDIR/share/doc/coin/DyLP/README should be available if DyLP is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_dylp" >&5
 echo "${ECHO_T}$coin_has_dylp" >&6
+  if test $coin_has_dylp != notGiven &&
+     test $coin_has_dylp != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of DyLP" >&5
+echo $ECHO_N "checking for source code location of DyLP... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $DYLPSRCDIR" >&5
+echo "${ECHO_T}$DYLPSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of DyLP" >&5
+echo $ECHO_N "checking for object code location of DyLP... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $DYLPOBJDIR" >&5
+echo "${ECHO_T}$DYLPOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory DyLP should be recursed into" >&5
 echo $ECHO_N "checking whether directory DyLP should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_dylp" != skipped &&
+  if test "$coin_has_dylp" != skipping &&
      test "$coin_has_dylp" != installed; then
     if test -r $srcdir/DyLP/configure; then
       coin_subdirs="$coin_subdirs DyLP"
@@ -21830,9 +21884,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Vol/README; then
+		     coin_has_vol=installed
+		     VOLINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21894,18 +21949,35 @@ fi
 if test $coin_has_vol = installed; then
   echo "$as_me:$LINENO: result: installed in $VOLINSTDIR" >&5
 echo "${ECHO_T}installed in $VOLINSTDIR" >&6
-  # Check for header
+  if test -r $VOLINSTDIR/share/doc/coin/Vol/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $VOLINSTDIR/share/doc/coin/Vol/README should be available if Vol is installed" >&5
+echo "$as_me: error: $VOLINSTDIR/share/doc/coin/Vol/README should be available if Vol is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_vol" >&5
 echo "${ECHO_T}$coin_has_vol" >&6
+  if test $coin_has_vol != notGiven &&
+     test $coin_has_vol != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Vol" >&5
+echo $ECHO_N "checking for source code location of Vol... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $VOLSRCDIR" >&5
+echo "${ECHO_T}$VOLSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Vol" >&5
+echo $ECHO_N "checking for object code location of Vol... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $VOLOBJDIR" >&5
+echo "${ECHO_T}$VOLOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory Vol should be recursed into" >&5
 echo $ECHO_N "checking whether directory Vol should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_vol" != skipped &&
+  if test "$coin_has_vol" != skipping &&
      test "$coin_has_vol" != installed; then
     if test -r $srcdir/Vol/configure; then
       coin_subdirs="$coin_subdirs Vol"
@@ -22034,9 +22106,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Osi/README; then
+		     coin_has_osi=installed
+		     OSIINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22098,18 +22171,35 @@ fi
 if test $coin_has_osi = installed; then
   echo "$as_me:$LINENO: result: installed in $OSIINSTDIR" >&5
 echo "${ECHO_T}installed in $OSIINSTDIR" >&6
-  # Check for header
+  if test -r $OSIINSTDIR/share/doc/coin/Osi/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $OSIINSTDIR/share/doc/coin/Osi/README should be available if Osi is installed" >&5
+echo "$as_me: error: $OSIINSTDIR/share/doc/coin/Osi/README should be available if Osi is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_osi" >&5
 echo "${ECHO_T}$coin_has_osi" >&6
+  if test $coin_has_osi != notGiven &&
+     test $coin_has_osi != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Osi" >&5
+echo $ECHO_N "checking for source code location of Osi... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $OSISRCDIR" >&5
+echo "${ECHO_T}$OSISRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Osi" >&5
+echo $ECHO_N "checking for object code location of Osi... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $OSIOBJDIR" >&5
+echo "${ECHO_T}$OSIOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory Osi should be recursed into" >&5
 echo $ECHO_N "checking whether directory Osi should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_osi" != skipped &&
+  if test "$coin_has_osi" != skipping &&
      test "$coin_has_osi" != installed; then
     if test -r $srcdir/Osi/configure; then
       coin_subdirs="$coin_subdirs Osi"
@@ -22238,9 +22328,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Cgl/README; then
+		     coin_has_cgl=installed
+		     CGLINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22302,18 +22393,35 @@ fi
 if test $coin_has_cgl = installed; then
   echo "$as_me:$LINENO: result: installed in $CGLINSTDIR" >&5
 echo "${ECHO_T}installed in $CGLINSTDIR" >&6
-  # Check for header
+  if test -r $CGLINSTDIR/share/doc/coin/Cgl/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CGLINSTDIR/share/doc/coin/Cgl/README should be available if Cgl is installed" >&5
+echo "$as_me: error: $CGLINSTDIR/share/doc/coin/Cgl/README should be available if Cgl is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_cgl" >&5
 echo "${ECHO_T}$coin_has_cgl" >&6
+  if test $coin_has_cgl != notGiven &&
+     test $coin_has_cgl != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Cgl" >&5
+echo $ECHO_N "checking for source code location of Cgl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CGLSRCDIR" >&5
+echo "${ECHO_T}$CGLSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Cgl" >&5
+echo $ECHO_N "checking for object code location of Cgl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CGLOBJDIR" >&5
+echo "${ECHO_T}$CGLOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory Cgl should be recursed into" >&5
 echo $ECHO_N "checking whether directory Cgl should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_cgl" != skipped &&
+  if test "$coin_has_cgl" != skipping &&
      test "$coin_has_cgl" != installed; then
     if test -r $srcdir/Cgl/configure; then
       coin_subdirs="$coin_subdirs Cgl"
@@ -22442,9 +22550,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cbc with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Cbc with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Cbc/README; then
+		     coin_has_cbc=installed
+		     CBCINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22506,18 +22615,35 @@ fi
 if test $coin_has_cbc = installed; then
   echo "$as_me:$LINENO: result: installed in $CBCINSTDIR" >&5
 echo "${ECHO_T}installed in $CBCINSTDIR" >&6
-  # Check for header
+  if test -r $CBCINSTDIR/share/doc/coin/Cbc/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CBCINSTDIR/share/doc/coin/Cbc/README should be available if Cbc is installed" >&5
+echo "$as_me: error: $CBCINSTDIR/share/doc/coin/Cbc/README should be available if Cbc is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_cbc" >&5
 echo "${ECHO_T}$coin_has_cbc" >&6
+  if test $coin_has_cbc != notGiven &&
+     test $coin_has_cbc != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Cbc" >&5
+echo $ECHO_N "checking for source code location of Cbc... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CBCSRCDIR" >&5
+echo "${ECHO_T}$CBCSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Cbc" >&5
+echo $ECHO_N "checking for object code location of Cbc... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CBCOBJDIR" >&5
+echo "${ECHO_T}$CBCOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory Cbc should be recursed into" >&5
 echo $ECHO_N "checking whether directory Cbc should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_cbc" != skipped &&
+  if test "$coin_has_cbc" != skipping &&
      test "$coin_has_cbc" != installed; then
     if test -r $srcdir/Cbc/configure; then
       coin_subdirs="$coin_subdirs Cbc"
@@ -22646,9 +22772,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of SYMPHONY with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of SYMPHONY with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/SYMPHONY/README; then
+		     coin_has_symphony=installed
+		     SYMPHONYINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22710,18 +22837,35 @@ fi
 if test $coin_has_symphony = installed; then
   echo "$as_me:$LINENO: result: installed in $SYMPHONYINSTDIR" >&5
 echo "${ECHO_T}installed in $SYMPHONYINSTDIR" >&6
-  # Check for header
+  if test -r $SYMPHONYINSTDIR/share/doc/coin/SYMPHONY/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $SYMPHONYINSTDIR/share/doc/coin/SYMPHONY/README should be available if SYMPHONY is installed" >&5
+echo "$as_me: error: $SYMPHONYINSTDIR/share/doc/coin/SYMPHONY/README should be available if SYMPHONY is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_symphony" >&5
 echo "${ECHO_T}$coin_has_symphony" >&6
+  if test $coin_has_symphony != notGiven &&
+     test $coin_has_symphony != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of SYMPHONY" >&5
+echo $ECHO_N "checking for source code location of SYMPHONY... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $SYMPHONYSRCDIR" >&5
+echo "${ECHO_T}$SYMPHONYSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of SYMPHONY" >&5
+echo $ECHO_N "checking for object code location of SYMPHONY... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $SYMPHONYOBJDIR" >&5
+echo "${ECHO_T}$SYMPHONYOBJDIR" >&6
+  fi
 fi
 
   echo "$as_me:$LINENO: checking whether directory SYMPHONY should be recursed into" >&5
 echo $ECHO_N "checking whether directory SYMPHONY should be recursed into... $ECHO_C" >&6
-  if test "$coin_has_symphony" != skipped &&
+  if test "$coin_has_symphony" != skipping &&
      test "$coin_has_symphony" != installed; then
     if test -r $srcdir/SYMPHONY/configure; then
       coin_subdirs="$coin_subdirs SYMPHONY"
