add no pkg-config fallback (not tested)

diff --git a/Cbc/configure b/Cbc/configure
--- a/Cbc/configure
+++ b/Cbc/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS PKG_CONFIG ac_pt_PKG_CONFIG COINDEPEND_LIBS COINDEPEND_CFLAGS COINDEPEND_DATA REQUIREDPACKAGES COIN_HAS_COINDEPEND_TRUE COIN_HAS_COINDEPEND_FALSE CLP_LIBS CLP_CFLAGS CLP_DATA COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE DYLP_LIBS DYLP_CFLAGS DYLP_DATA COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE VOL_LIBS VOL_CFLAGS VOL_DATA COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE OSITESTS_LIBS OSITESTS_CFLAGS OSITESTS_DATA COIN_HAS_OSITESTS_TRUE COIN_HAS_OSITESTS_FALSE SAMPLE_LIBS SAMPLE_CFLAGS SAMPLE_DATA COIN_HAS_SAMPLE_TRUE COIN_HAS_SAMPLE_FALSE NETLIB_LIBS NETLIB_CFLAGS NETLIB_DATA COIN_HAS_NETLIB_TRUE COIN_HAS_NETLIB_FALSE MIPLIB3_LIBS MIPLIB3_CFLAGS MIPLIB3_DATA COIN_HAS_MIPLIB3_TRUE COIN_HAS_MIPLIB3_FALSE CPX_LIBS CPX_CFLAGS CPX_DATA COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE GLPK_LIBS GLPK_CFLAGS GLPK_DATA COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE MSK_LIBS MSK_CFLAGS MSK_DATA COIN_HAS_MSK_TRUE COIN_HAS_MSK_FALSE XPR_LIBS XPR_CFLAGS XPR_DATA COIN_HAS_XPR_TRUE COIN_HAS_XPR_FALSE ASL_LIBS ASL_CFLAGS ASL_DATA COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE CBC_BUILD_CBC_GENERIC_TRUE CBC_BUILD_CBC_GENERIC_FALSE LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS PKG_CONFIG ac_pt_PKG_CONFIG COINDEPEND_LIBS COINDEPEND_CFLAGS COINDEPEND_DATA REQUIREDPACKAGES COIN_HAS_COINDEPEND_TRUE COIN_HAS_COINDEPEND_FALSE CLP_LIBS CLP_CFLAGS CLP_DATA COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE DYLP_LIBS DYLP_CFLAGS DYLP_DATA COIN_HAS_DYLP_TRUE COIN_HAS_DYLP_FALSE VOL_LIBS VOL_CFLAGS VOL_DATA COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE OSITESTS_LIBS OSITESTS_CFLAGS OSITESTS_DATA COIN_HAS_OSITESTS_TRUE COIN_HAS_OSITESTS_FALSE SAMPLE_LIBS SAMPLE_CFLAGS SAMPLE_DATA COIN_HAS_SAMPLE_TRUE COIN_HAS_SAMPLE_FALSE NETLIB_LIBS NETLIB_CFLAGS NETLIB_DATA COIN_HAS_NETLIB_TRUE COIN_HAS_NETLIB_FALSE MIPLIB3_LIBS MIPLIB3_CFLAGS MIPLIB3_DATA COIN_HAS_MIPLIB3_TRUE COIN_HAS_MIPLIB3_FALSE COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE OSISRCDIR OSIOBJDIR OSIDOCDIR COIN_HAS_OSI_TRUE COIN_HAS_OSI_FALSE CGLSRCDIR CGLOBJDIR CGLDOCDIR COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE CLPSRCDIR CLPOBJDIR CLPDOCDIR CPX_LIBS CPX_CFLAGS CPX_DATA COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE GLPK_LIBS GLPK_CFLAGS GLPK_DATA COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE MSK_LIBS MSK_CFLAGS MSK_DATA COIN_HAS_MSK_TRUE COIN_HAS_MSK_FALSE XPR_LIBS XPR_CFLAGS XPR_DATA COIN_HAS_XPR_TRUE COIN_HAS_XPR_FALSE ASL_LIBS ASL_CFLAGS ASL_DATA COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE CBC_BUILD_CBC_GENERIC_TRUE CBC_BUILD_CBC_GENERIC_FALSE LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22116,7 +22116,319 @@ fi
 
 
 
-#TODO! fallbacks!
+# fallbacks for CoinDepend and Clp if no pkg-config is available
+if test "$coin_has_coindepend" != yes ; then
+  echo "$as_me:$LINENO: checking for COIN project CoinUtils" >&5
+echo $ECHO_N "checking for COIN project CoinUtils... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_coinutils=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = CoinUtils; then
+      coin_has_coinutils=skipping
+    fi
+  done
+fi
+
+if test $coin_has_coinutils != skipping; then
+  if test $PACKAGE_TARNAME = coinutils; then
+    coin_has_coinutils=.
+  else
+    if test -d $srcdir/../CoinUtils; then
+      coin_has_coinutils=../CoinUtils
+    fi
+  fi
+fi
+
+if test $coin_has_coinutils != unavailable &&
+   test $coin_has_coinutils != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_COINUTILS 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  COINUTILSSRCDIR=`cd $srcdir/$coin_has_coinutils; pwd`
+
+  COINUTILSOBJDIR=`pwd`/$coin_has_coinutils
+
+  COINUTILSDOCDIR=$abs_lib_dir/../share/doc/coin/CoinUtils
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_coinutils != unavailable &&
+                test $coin_has_coinutils != skipping; then
+  COIN_HAS_COINUTILS_TRUE=
+  COIN_HAS_COINUTILS_FALSE='#'
+else
+  COIN_HAS_COINUTILS_TRUE='#'
+  COIN_HAS_COINUTILS_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
+echo "${ECHO_T}$coin_has_coinutils" >&6
+
+  echo "$as_me:$LINENO: checking for COIN project Osi" >&5
+echo $ECHO_N "checking for COIN project Osi... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_osi=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = Osi; then
+      coin_has_osi=skipping
+    fi
+  done
+fi
+
+if test $coin_has_osi != skipping; then
+  if test $PACKAGE_TARNAME = osi; then
+    coin_has_osi=.
+  else
+    if test -d $srcdir/../Osi; then
+      coin_has_osi=../Osi
+    fi
+  fi
+fi
+
+if test $coin_has_osi != unavailable &&
+   test $coin_has_osi != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_OSI 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  OSISRCDIR=`cd $srcdir/$coin_has_osi; pwd`
+
+  OSIOBJDIR=`pwd`/$coin_has_osi
+
+  OSIDOCDIR=$abs_lib_dir/../share/doc/coin/Osi
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_osi != unavailable &&
+                test $coin_has_osi != skipping; then
+  COIN_HAS_OSI_TRUE=
+  COIN_HAS_OSI_FALSE='#'
+else
+  COIN_HAS_OSI_TRUE='#'
+  COIN_HAS_OSI_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_osi" >&5
+echo "${ECHO_T}$coin_has_osi" >&6
+
+  echo "$as_me:$LINENO: checking for COIN project Cgl" >&5
+echo $ECHO_N "checking for COIN project Cgl... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_cgl=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = Cgl; then
+      coin_has_cgl=skipping
+    fi
+  done
+fi
+
+if test $coin_has_cgl != skipping; then
+  if test $PACKAGE_TARNAME = cgl; then
+    coin_has_cgl=.
+  else
+    if test -d $srcdir/../Cgl; then
+      coin_has_cgl=../Cgl
+    fi
+  fi
+fi
+
+if test $coin_has_cgl != unavailable &&
+   test $coin_has_cgl != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_CGL 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  CGLSRCDIR=`cd $srcdir/$coin_has_cgl; pwd`
+
+  CGLOBJDIR=`pwd`/$coin_has_cgl
+
+  CGLDOCDIR=$abs_lib_dir/../share/doc/coin/Cgl
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_cgl != unavailable &&
+                test $coin_has_cgl != skipping; then
+  COIN_HAS_CGL_TRUE=
+  COIN_HAS_CGL_FALSE='#'
+else
+  COIN_HAS_CGL_TRUE='#'
+  COIN_HAS_CGL_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_cgl" >&5
+echo "${ECHO_T}$coin_has_cgl" >&6
+
+  if test $coin_has_coinutils != notGiven && test $coin_has_coinutils != skipping ; then
+    COINDEPEND_CFLAGS="-I`${CYGPATH_W} ${COINUTILSSRCDIR}/src` -I`${CYGPATH_W} ${COINUTILSOBJDIR}/inc`"
+    COINDEPEND_LIBS="${COINUTILSOBJDIR}/src/libCoinUtils.la `cat ${COINUTILSOBJDIR}/coinutils_addlibs.txt`"
+  else
+    { { echo "$as_me:$LINENO: error: \"Required package CoinUtils unavailable.\"" >&5
+echo "$as_me: error: \"Required package CoinUtils unavailable.\"" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test $coin_has_osi != notGiven && test $coin_has_osi != skipping ; then
+    COINDEPEND_CFLAGS="${COINDEPEND_CFLAGS} -I`${CYGPATH_W} ${OSISRCDIR}/src` -I`${CYGPATH_W} ${OSIOBJDIR}/inc`"
+    COINDEPEND_LIBS="${COINDEPEND_LIBS} ${OSIOBJDIR}/src/libOsi.la `cat ${OSIOBJDIR}/osi_addlibs.txt`"
+  else
+    { { echo "$as_me:$LINENO: error: \"Required package Osi unavailable.\"" >&5
+echo "$as_me: error: \"Required package Osi unavailable.\"" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test $coin_has_cgl != notGiven && test $coin_has_cgl != skipping ; then
+    COINDEPEND_CFLAGS="${COINDEPEND_CFLAGS} -I`${CYGPATH_W} ${CGLSRCDIR}/src` -I`${CYGPATH_W} ${CGLOBJDIR}/inc` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglAllDifferent` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglClique` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglDuplicateRow` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglFlowCover` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglGomory` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglKnapsackCover` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglLandP` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglLiftAndProject` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglMixedIntegerRounding` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglMixedIntegerRounding2` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglOddHole` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglPreProcess` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglProbing` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglRedSplit` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglResidualCapacity` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglSimpleRounding` -I`${CYGPATH_W} ${CGLSRCDIR}/src/CglTwomir`"
+    COINDEPEND_LIBS="${COINDEPEND_LIBS} ${CGLOBJDIR}/src/libCgl.la `cat ${CGLOBJDIR}/cgl_addlibs.txt`"
+  else
+    { { echo "$as_me:$LINENO: error: \"Required package Cgl unavailable.\"" >&5
+echo "$as_me: error: \"Required package Cgl unavailable.\"" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  coin_has_coindepend=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_COINDEPEND 1
+_ACEOF
+
+else
+  # to please configure
+
+
+if test 0 = 1; then
+  COIN_HAS_COINUTILS_TRUE=
+  COIN_HAS_COINUTILS_FALSE='#'
+else
+  COIN_HAS_COINUTILS_TRUE='#'
+  COIN_HAS_COINUTILS_FALSE=
+fi
+
+
+
+if test 0 = 1; then
+  COIN_HAS_OSI_TRUE=
+  COIN_HAS_OSI_FALSE='#'
+else
+  COIN_HAS_OSI_TRUE='#'
+  COIN_HAS_OSI_FALSE=
+fi
+
+
+
+if test 0 = 1; then
+  COIN_HAS_CGL_TRUE=
+  COIN_HAS_CGL_FALSE='#'
+else
+  COIN_HAS_CGL_TRUE='#'
+  COIN_HAS_CGL_FALSE=
+fi
+
+fi
+
+if test "$coin_has_clp" != yes ; then
+  echo "$as_me:$LINENO: checking for COIN project Clp" >&5
+echo $ECHO_N "checking for COIN project Clp... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_clp=unavailable
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = Clp; then
+      coin_has_clp=skipping
+    fi
+  done
+fi
+
+if test $coin_has_clp != skipping; then
+  if test $PACKAGE_TARNAME = clp; then
+    coin_has_clp=.
+  else
+    if test -d $srcdir/../Clp; then
+      coin_has_clp=../Clp
+    fi
+  fi
+fi
+
+if test $coin_has_clp != unavailable &&
+   test $coin_has_clp != skipping; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_CLP 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  CLPSRCDIR=`cd $srcdir/$coin_has_clp; pwd`
+
+  CLPOBJDIR=`pwd`/$coin_has_clp
+
+  CLPDOCDIR=$abs_lib_dir/../share/doc/coin/Clp
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_clp != unavailable &&
+                test $coin_has_clp != skipping; then
+  COIN_HAS_CLP_TRUE=
+  COIN_HAS_CLP_FALSE='#'
+else
+  COIN_HAS_CLP_TRUE='#'
+  COIN_HAS_CLP_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_clp" >&5
+echo "${ECHO_T}$coin_has_clp" >&6
+
+  if test $coin_has_clp != notGiven && test $coin_has_clp != skipping ; then
+    CLP_CFLAGS="-I`${CYGPATH_W} ${CLPSRCDIR}/src` -I`${CYGPATH_W} ${CLPSRCDIR}/src/OsiClp` -I`${CYGPATH_W} ${CLPOBJDIR}/inc`"
+    CLP_LIBS="${CLPOBJDIR}/src/libClp.la ${CLPOBJDIR}/src/OsiClp/libOsiClp.la `cat ${CLPOBJDIR}/clp_addlibs.txt`"
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_CLP 1
+_ACEOF
+
+  else
+    { { echo "$as_me:$LINENO: error: \"Required package Clp unavailable.\"" >&5
+echo "$as_me: error: \"Required package Clp unavailable.\"" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
 
 #############################################################################
 #                            Third party solvers                            #
@@ -23631,6 +23943,55 @@ echo "$as_me: error: conditional \"COIN_HAS_MIPLIB3\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COIN_HAS_COINUTILS_TRUE}" && test -z "${COIN_HAS_COINUTILS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_OSI_TRUE}" && test -z "${COIN_HAS_OSI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_CGL_TRUE}" && test -z "${COIN_HAS_CGL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CGL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_CGL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_COINUTILS_TRUE}" && test -z "${COIN_HAS_COINUTILS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_OSI_TRUE}" && test -z "${COIN_HAS_OSI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_OSI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_CGL_TRUE}" && test -z "${COIN_HAS_CGL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CGL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_CGL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_CLP_TRUE}" && test -z "${COIN_HAS_CLP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CLP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_CLP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${COIN_HAS_CPX_TRUE}" && test -z "${COIN_HAS_CPX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_CPX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24353,6 +24714,24 @@ s,@MIPLIB3_CFLAGS@,$MIPLIB3_CFLAGS,;t t
 s,@MIPLIB3_DATA@,$MIPLIB3_DATA,;t t
 s,@COIN_HAS_MIPLIB3_TRUE@,$COIN_HAS_MIPLIB3_TRUE,;t t
 s,@COIN_HAS_MIPLIB3_FALSE@,$COIN_HAS_MIPLIB3_FALSE,;t t
+s,@COINUTILSSRCDIR@,$COINUTILSSRCDIR,;t t
+s,@COINUTILSOBJDIR@,$COINUTILSOBJDIR,;t t
+s,@COINUTILSDOCDIR@,$COINUTILSDOCDIR,;t t
+s,@COIN_HAS_COINUTILS_TRUE@,$COIN_HAS_COINUTILS_TRUE,;t t
+s,@COIN_HAS_COINUTILS_FALSE@,$COIN_HAS_COINUTILS_FALSE,;t t
+s,@OSISRCDIR@,$OSISRCDIR,;t t
+s,@OSIOBJDIR@,$OSIOBJDIR,;t t
+s,@OSIDOCDIR@,$OSIDOCDIR,;t t
+s,@COIN_HAS_OSI_TRUE@,$COIN_HAS_OSI_TRUE,;t t
+s,@COIN_HAS_OSI_FALSE@,$COIN_HAS_OSI_FALSE,;t t
+s,@CGLSRCDIR@,$CGLSRCDIR,;t t
+s,@CGLOBJDIR@,$CGLOBJDIR,;t t
+s,@CGLDOCDIR@,$CGLDOCDIR,;t t
+s,@COIN_HAS_CGL_TRUE@,$COIN_HAS_CGL_TRUE,;t t
+s,@COIN_HAS_CGL_FALSE@,$COIN_HAS_CGL_FALSE,;t t
+s,@CLPSRCDIR@,$CLPSRCDIR,;t t
+s,@CLPOBJDIR@,$CLPOBJDIR,;t t
+s,@CLPDOCDIR@,$CLPDOCDIR,;t t
 s,@CPX_LIBS@,$CPX_LIBS,;t t
 s,@CPX_CFLAGS@,$CPX_CFLAGS,;t t
 s,@CPX_DATA@,$CPX_DATA,;t t
