rerun autotools; OsiCpx.hpp does not include cplex.h anymore - need to do by ourself

diff --git a/Cbc/configure b/Cbc/configure
--- a/Cbc/configure
+++ b/Cbc/configure
@@ -21338,7 +21338,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-	   for fnm in MSK_openmosek ; do
+	   for fnm in MSK_makeenv ; do
 	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with MSK" >&5
 echo $ECHO_N "checking whether symbol $fnm is available with MSK... $ECHO_C" >&6
 	     cat >conftest.$ac_ext <<_ACEOF
@@ -21401,8 +21401,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 	   if test x"$coin_MSK_link" = xyes ; then
 	     LIBS="$coin_save_LIBS"
 	   else
-	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) MSK_openmosek with MSK" >&5
-echo "$as_me: error: Cannot find symbol(s) MSK_openmosek with MSK" >&2;}
+	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) MSK_makeenv with MSK" >&5
+echo "$as_me: error: Cannot find symbol(s) MSK_makeenv with MSK" >&2;}
    { (exit 1); exit 1; }; }
 	   fi
 	 fi
@@ -21809,7 +21809,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-	   for fnm in XPRSsetintcontrol ; do
+	   for fnm in XPRSinit ; do
 	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with XPR" >&5
 echo $ECHO_N "checking whether symbol $fnm is available with XPR... $ECHO_C" >&6
 	     cat >conftest.$ac_ext <<_ACEOF
@@ -21872,8 +21872,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 	   if test x"$coin_XPR_link" = xyes ; then
 	     LIBS="$coin_save_LIBS"
 	   else
-	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) XPRSsetintcontrol with XPR" >&5
-echo "$as_me: error: Cannot find symbol(s) XPRSsetintcontrol with XPR" >&2;}
+	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) XPRSinit with XPR" >&5
+echo "$as_me: error: Cannot find symbol(s) XPRSinit with XPR" >&2;}
    { (exit 1); exit 1; }; }
 	   fi
 	 fi
